compiler:
  - clang
  - gcc

before_script:
   - gem install travis

script:
   -

after_script:
   - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
   - chmod +x trigger.sh
   - ./trigger.sh stephanmg vr-grids development $TRAVIS_ACCESS_TOKEN ""
